# get user

GET http://localhost:4000/users/654282b0b55f638081203952 HTTP/1.1
Content-Type: application/json

{
  "email": "go@gmail.com"
}

###

# create user

POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
  "email": "Magotаfs@gmail.com",
  "name": "baduk",
  "password": "badi228",
  "isPro": false
}

###

# login

GET  http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
  "email": "Magots@gmail.com",
  "password": "badi228"
}

###

# auth

GET http://localhost:4000/auth HTTP/1.1
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDkxYTEzZDM4NGQxNWZhNjc3Y2Y5YSIsImVtYWlsIjoidGVzdEBkZC5jb20iLCJpc1BybyI6ZmFsc2UsIm5hbWUiOiJDaGxlbml4UFdOWiIsImV4cCI6MTY5OTM3NjAxOSwiaWF0IjoxNjk5Mjg5NjE5fQ.zTEal1usym09-GttQiVTkGEiATG7qLdqjJoIjtJStMI

###

# post avatar

POST http://localhost:4000/users/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDhhMjdlMjMwNGNmZmNkZjEwY2Q3MyIsImVtYWlsIjoiTWFnb3RzQGdtYWlsLmNvbSIsImlzUHJvIjpmYWxzZSwibmFtZSI6ImJhZHVrIiwiZXhwIjoxNjk5MzY5NjEzLCJpYXQiOjE2OTkyODMyMTN9.MJSJSDGb526mO7Fv5_2iW_hvx8-ZBr8f8pjrAABrpE0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="1b6e0650b5aafe19efe20aa80f.jpg"
Content-Type: image/png

< /Users/gamerdaddy/Downloads/1b6e0650b5aafe19efe20aa80f.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
