# get user

GET http://localhost:4000/users/dsdfds HTTP/1.1
Content-Type: application/json

{
  "email": "Oleg@gmail.com"
}

###

# create user

POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
  "email": "badukkk@gmail.com",
  "name": "baduk",
  "avatar": "vvv.jpg",
  "password": "badi228",
  "isPro": false
}

###


# logout

DELETE http://localhost:4000/login HTTP/1.1
Content-Type: application/json

###

# login

GET  http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
  "email": "bad@lol.com",
  "password": "bad"
}

###

# auth

GET http://localhost:4000/auth HTTP/1.1
Authorization: 123

###
