# get user

GET http://localhost:4000/users/654282b0b55f638081203952 HTTP/1.1
Content-Type: application/json

{
  "email": "go@gmail.com"
}

###

# create user

POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
  "email": "Magots@gmail.com",
  "name": "baduk",
  "password": "badi228",
  "isPro": false
}

###

# login

GET  http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
  "email": "Magots@gmail.com",
  "password": "badi228"
}

###

# auth

GET http://localhost:4000/auth HTTP/1.1
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDg5ZDQ2NWEwNDI4ODgzYzVhYzVmYiIsImVtYWlsIjoiTWFnb3RzQGdtYWlsLmNvbSIsImlzUHJvIjpmYWxzZSwibmFtZSI6ImJhZHVrIiwiZXhwIjoxNjk5MzQ0MDg3LCJpYXQiOjE2OTkyNTc2ODd9.V2KzPFWLFEZE5trlx8MI1Xv7bYZ9AiccfGNNEUIUPnY

###

# post avatar

POST http://localhost:4000/users/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDg5ZDQ2NWEwNDI4ODgzYzVhYzVmYiIsImVtYWlsIjoiTWFnb3RzQGdtYWlsLmNvbSIsImlzUHJvIjpmYWxzZSwibmFtZSI6ImJhZHVrIiwiZXhwIjoxNjk5MzQ0MDg3LCJpYXQiOjE2OTkyNTc2ODd9.V2KzPFWLFEZE5trlx8MI1Xv7bYZ9AiccfGNNEUIUPnY

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="1b6e0650b5aafe19efe20aa80f.jpg"
Content-Type: image/png

< /Users/gamerdaddy/Downloads/80f146da-c530-4f5d-ab86-9992f3a9e945.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
