export const Component = {
  RestApplication: 'RestApplication',
  Logger: 'Logger',
  Config: 'Config',
  DBClient: 'DBClient',
  UserService: 'UserService',
  UserModel: 'UserModel',
  RentModel: 'RentModel',
  RentService: 'RentService',
  CommentModel: 'CommentModel',
  CommentService: 'CommentService',
  CommentController: 'CommentController',
  RentController: 'RentController',
  UserController: 'UserController',
} as const;
